### ISSUE TITLE
Disable in island sanctuary?

### ISSUE THREAD

**Issue by DenL** [InitialDet/MinionRoulette#1]
Currently if you try to summon a minion in Island Sanctuary, that minion would be 'recalled' from where they are 'assigned'. Having your favorite minion assigned and having this plugin means that you would possibly randomly recall a minion whenever you zone in. Adding an option to disable this in island sanctuary would be great, thank you!

**Comment by InitialDet** [comment]
I didn't expect this bug, it should be good now.
