### ISSUE TITLE
Internal Error in Dalamud

### ISSUE THREAD

**Issue by SyniRon** [InitialDet/MinionRoulette#2]
![ffxiv_dx11_5CeI8Bk3t9](https://user-images.githubusercontent.com/66834451/212212621-878ed5ae-27aa-4974-984e-662de649e7b6.png)

This error occurs upon changing zone with a minion out (in this case, Namingway)

Happens consistently upon every zone change.

Error stops with no minion or with plugin disabled.

Have not tested with all other plugins disabled but will be happy to and provide logs if you're unable to reproduce.

**Comment by InitialDet** [comment]
I think the release was compiled with an outdated version. It should be good now

**Comment by SyniRon** [comment]
Confirmed working with version v1.1.2.2 on dalamud staging 235137c

Thanks so much for the plugin and the rapid fix!
